name: Build and Deploy Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Java version from build.gradle
        id: extract-java-version
        run: |
          JAVA_VERSION=$(grep -oP "javaVersion\s*=\s*'\K[0-9]+" build.gradle || echo "11")
          echo "java-version=$JAVA_VERSION" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.java-version }}
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Publish plugin
        run: |
          ./gradlew check
          ./gradlew runPluginVerifier
        env:
            ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
            CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
